// Code generated by MockGen. DO NOT EDIT.
// Source: manager.go

// Package session is a generated GoMock package.
package session

import (
	http "net/http"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockSessionManagerRepo is a mock of SessionManagerRepo interface.
type MockSessionManagerRepo struct {
	ctrl     *gomock.Controller
	recorder *MockSessionManagerRepoMockRecorder
}

// MockSessionManagerRepoMockRecorder is the mock recorder for MockSessionManagerRepo.
type MockSessionManagerRepoMockRecorder struct {
	mock *MockSessionManagerRepo
}

// NewMockSessionManagerRepo creates a new mock instance.
func NewMockSessionManagerRepo(ctrl *gomock.Controller) *MockSessionManagerRepo {
	mock := &MockSessionManagerRepo{ctrl: ctrl}
	mock.recorder = &MockSessionManagerRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSessionManagerRepo) EXPECT() *MockSessionManagerRepoMockRecorder {
	return m.recorder
}

// Check mocks base method.
func (m *MockSessionManagerRepo) Check(r *http.Request) (*Session, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Check", r)
	ret0, _ := ret[0].(*Session)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Check indicates an expected call of Check.
func (mr *MockSessionManagerRepoMockRecorder) Check(r interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Check", reflect.TypeOf((*MockSessionManagerRepo)(nil).Check), r)
}

// Create mocks base method.
func (m *MockSessionManagerRepo) Create(w http.ResponseWriter, userID, login string) (*Session, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", w, userID, login)
	ret0, _ := ret[0].(*Session)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Create indicates an expected call of Create.
func (mr *MockSessionManagerRepoMockRecorder) Create(w, userID, login interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockSessionManagerRepo)(nil).Create), w, userID, login)
}

// GetSecret mocks base method.
func (m *MockSessionManagerRepo) GetSecret() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSecret")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetSecret indicates an expected call of GetSecret.
func (mr *MockSessionManagerRepoMockRecorder) GetSecret() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSecret", reflect.TypeOf((*MockSessionManagerRepo)(nil).GetSecret))
}
